example: c_example.c
	gcc -shared -I/usr/include/python2.7/ -lpython2.7 -o c_example.so c_example.c -shared -fPIC

wordnet: wordnet_c.c
	gcc -shared -I/usr/include/python2.7/ -lpython2.7 -o wordnet_c.so wordnet_c.c -shared -fPIC